sudo: false

language: php

php:
  - 7.1
  - 7.2
  - 7.3

env:
#  - SYMFONY_VERSION=2.5.*
#  - SYMFONY_VERSION=2.6.*
#  - SYMFONY_VERSION=2.7.*
#  - SYMFONY_VERSION=3.*
  - SYMFONY_VERSION=4.*

#matrix:
#  exclude:
#    - php: 7.0
#      env: SYMFONY_VERSION=4.*

cache:
  directories:
    - $HOME/.composer/cache

install:
  - COMPOSER_MEMORY_LIMIT=-1 travis_retry composer self-update

before_script:
  - COMPOSER_MEMORY_LIMIT=-1 travis_retry composer require symfony/framework-bundle:${SYMFONY_VERSION} --prefer-source
  - COMPOSER_MEMORY_LIMIT=-1 travis_retry composer install --prefer-source

script:
  - phpdbg -qrr bin/phpunit --configuration phpunit.xml.dist --coverage-clover clover.xml --coverage-text

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover clover.xml

notifications:
  email:
    - vaillentin@gmail.com
